# Generated by Django 6.1 on 2026-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('counties_served', models.JSONField(default=list)),
                ('cities_served', models.JSONField(default=list)),
                ('needs_addressed', models.JSONField(default=list)),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accepted_insurance', models.JSONField(default=list)),
                ('supported_languages', models.JSONField(default=list)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_excerpt', models.TextField(blank=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('other', 'Other')], max_length=30)),
                ('insurance_type', models.CharField(blank=True, max_length=100)),
                ('wheelchair', models.BooleanField(default=False)),
                ('needs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
