# Generated by Django 6.0.8 on 2026-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityresource',
            name='healthcare_specialties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='communityresource',
            name='population_served',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='communityresource',
            name='program_purposes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='communityresource',
            name='provider_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='communityresource',
            name='service_modalities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='healthcare_specialties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='population_context',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='program_purposes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='service_modalities',
            field=models.JSONField(default=list),
        ),
    ]
