# Generated by Django 6.0.8 on 2026-08-25 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_communityresource_healthcare_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('collecting', 'Collecting information'), ('ready', 'Ready for search'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='collecting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='referrals.referralrequest')),
            ],
        ),
    ]
